[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "phcreery", email = "phcreery@gmail.com"},
]
dependencies = [
    "ipykernel>=6.22.0",
    "pandas>=2.0.0",
    "numpy>=1.24.2",
    "sympy>=1.11.1",
    "matplotlib>=3.7.1",
    "pyvista[trame]>=0.38.5",
    "trame>=2.3.2",
    "setuptools>=67.6.1",
    "ipywidgets>=8.0.6",
    "vedo>=2023.4.4",
    "trame-vtk>=2.4.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}
